Enhancement: mypy
jolly-good-toolbelt/tableread pull request #3
Opened 2019-06-24 13:07 UTC by bradsbrown

Add type hints and Mypy checking to `tableread`.

Updated docs for review here: https://bradsbrown.github.io/tableread/tableread.html

2019-06-24 13:20 UTC, brolewis approved these changes
This PR does indeed `mypy` all the things, therefore I approve.

2019-06-24 13:33 UTC, ecedmondson approved these changes

2019-06-25 14:00 UTC, rbcasperson requested changes
A good number of thoughts from me. Forgive any lack of python types knowledge from me as I havent really dug deeply into it yet.

2019-06-25 14:00 UTC, rbcasperson commented on poetry.lock
> +python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"
This is caused by sphinx? Just seems odd to see this based on the requirements of 3.6 in the pyproject.toml file. It's in the lock file though, so 🤷‍♂

2019-06-25 14:00 UTC, rbcasperson commented on tableread/__init__.py
> +tabletext = str
Hmmm are this supposed to be type hints? Looks like you're just assigning those variables to the built-in `str` function...

2019-06-25 14:00 UTC, rbcasperson commented on tableread/__init__.py
> +def get_specific_attr_matcher(key: str, value: Any):
I'm surprised to see `Any` here. Seems like is should be `str` since it calls `.lower()`.

2019-06-25 14:00 UTC, rbcasperson commented on tableread/__init__.py
> +tabletext = str
OK I see what this is here now. Just kind of odd to me to that a variable is set to a typing. I'd expect a different naming convention so it is easy to see what is a type declaration and what is just a variable. Maybe that is calling this `Filepath` and `TableText` to match what is in the `typing` module. I'm not familiar enough with python typings to know if there is a convention or not, but at the very least, I think a comment saying these are type declarations.

2019-06-25 14:00 UTC, rbcasperson commented on tableread/__init__.py
> +    data_format: Optional[Any] = None
1) Optional[Any] seems kind of redundant. Doesn't `Any` include `None`? Also, I don't like seeing the `Any` there. Isn't there something more specific you can expect? It looks like you wanted `Callable` in this case.

2) Why does just this line have a type hint and not the preceding ones as well? I didn't think Python did implicit typing.

2019-06-25 14:00 UTC, rbcasperson commented on tableread/__init__.py
> +    def __getitem__(self, key: Any):
Again, I don't like seeing `Any` unless it _really_ means anything. This is a used as a key, so it can't be something like a list say. Is there an `Immutable` type declaration?

2019-06-25 14:00 UTC, rbcasperson commented on tableread/__init__.py
> +tabletext = str
Also, seeing the use cases, I think `tabletext` isn't the most obvious name. It is used for `rst_string`, so I think that makes more sense, though I also like `filecontents` to match `filepath`, which I think captures the essence of the types.

2019-06-25 14:59 UTC, bradsbrown commented on tableread/__init__.py
> +tabletext = str
Yeah, type aliases for clarity are a idiomatic thing in `mypy` from what I've seen, but I do like the idea of the naming rework. Making that change.

2019-06-25 15:00 UTC, bradsbrown commented on tableread/__init__.py
> +def get_specific_attr_matcher(key: str, value: Any):
`:headslam:` Yeah, I was thinking too broadly when I set that up, didn't consider that the value there is _always_ coming from a table, and so will _always_ be a string.

2019-06-25 15:04 UTC, bradsbrown commented on tableread/__init__.py
> +    data_format: Optional[Any] = None
`mypy` will do implicit typing when it checks, so it was barking when I had `data_format = None` then set it to other types in the subclasses unless I specify that it won't always be `None`. It seems unnecessary to spec types for the rest of the class attributes that are static, but if we really want that we could add it, I guess.

You are correct that the `Optional[]` wrapper is extraneous, though. I'll drop that.

2019-06-25 15:12 UTC, bradsbrown commented on tableread/__init__.py
> +    def __getitem__(self, key: Any):
I can narrow this one down as well.

2019-06-25 15:18 UTC, bradsbrown commented on poetry.lock
> +python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"
This is the spec in the latest version of `pyyaml`: https://github.com/yaml/pyyaml/blob/master/setup.py#L314. I'm guessing that it just got updated as part of the re-lock.

2019-06-25 17:49 UTC, rbcasperson approved these changes
Thanks for the recent changes! LGTM, though I'll have to do my research on mypy.

2019-06-25 17:49 UTC, merged